In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("C:\\Users\\prana\\Downloads\\4ab1e23f-3262-4bd3-adbf-f72f0119108b.csv")
data.head(20)

,_id,date,site,parameter,index_value,description,health_advisory,health_effects
0,1,2016-01-01,Lawrenceville,PM25B,25,Good,NaN,NaN
1,2,2016-01-01,Flag Plaza,CO,0,Good,NaN,NaN
2,3,2016-01-01,Harrison Township,OZONE,31,Good,NaN,NaN
3,4,2016-01-01,Avalon,SO2,10,Good,NaN,NaN
4,5,2016-01-01,Lincoln,PM25,35,Good,NaN,NaN
5,6,2016-01-01,Lincoln,PM10,11,Good,NaN,NaN
6,7,2016-01-01,South Fayette,SO2,3,Good,NaN,NaN
7,8,2016-01-01,North Braddock,PM10B,12,Good,NaN,NaN
8,9,2016-01-01,Parkway East,CO,4,Good,NaN,NaN
9,10,2016-01-01,Flag Plaza,PM10,7,Good,NaN,NaN
10,11,2016-01-01,Liberty 2,PM25(2),28,Good,NaN,NaN
11,12,2016-01-01,Lawrenceville 2,SO2,1,Good,NaN,NaN
12,13,2016-01-01,Lawrenceville 2,CO,2,Good,NaN,NaN
13,14,2016-01-01,Harrison Township,NO2,3,Good,NaN,NaN
14,15,2016-01-01,Parkway East,NO2,6,Good,NaN,NaN
15,16,2016-01-01,Lawrenceville,OZONE,31,Good,NaN,NaN
16,17,2016-01-01,Liberty 2,PM10,6,Good,NaN,NaN
17,18,2016-01-01,Parkway East,PM25T,30,Good,NaN,NaN
18,19,2016-01-01,North Braddock,SO2,1,Good,NaN,NaN
19,20,2016-01-01,Glassport High Street,PM10,6,Good,NaN,NaN